---
- name: Plan
  terraform:
    project_path: "{{ project_dir }}"
    plan_file: 'tfplan'
    lock: true
    state: planned
  tags: 
    - terraform_plan

- name: Apply
  terraform:
    project_path: "{{ project_dir }}"
    lock: true
    state: present
  tags:
    - terraform_plan
    
- name: Destroy
  terraform:
    project_patch: "{{ project_dir }}"
    lock: true
    state: absent
  tags:
    - terraform_destroy

