---
- name: Install packages requirements
  package: name={{item}} state=latest
  with_items:
    - wget
  tags:
    - terraform_install
    - terraform_plan

- name: Install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_linux_amd64.zip
    dest: /usr/bin
    remote_src: True
  tags:
    - terraform_install
    - terraform_plan

- name: Plan
  terraform:
    project_path: "{{ project_dir }}"
    plan_file: 'tfplan'
    lock: true
    state: planned
  tags: 
    - terraform_plan

- name: Apply
  terraform:
    project_path: "{{ project_dir }}"
    lock: true
    state: present
  tags:
    - terraform_plan
    
- name: Destroy
  terraform:
    project_patch: "{{ project_dir }}"
    lock: true
    state: absent
  tags:
    - terraform_destroy
