---
- name: Download certbot-auto
  get_url:
    uri: https://dl.eff.org/certbot-auto
    dest: /us/local/bin
    mode: a+x

- name: Install packets requirements
  package: pkg="{{ item }}"
  with_items:
    - yum-utils
    - python

- name: Generate strong DHE parameter {{ default_domain }}
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048 creates=/etc/ssl/dhparam.pem

- name: Create directory for letsencrypt
  file: path="{{ item }}" state=diretoty owner=nginx group=nginx
  with_items:
   - /var/lib/letsencrypt/.well-known
   - /etc/nginx/snippets



  