language: python
python: '2.7'
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
jobs:
  include:
  - stage: deploy_dev
    if: branch = desenv AND NOT type IN (pull_request)
    before_install:
    - openssl aes-256-cbc -K $encrypted_138890a96bfe_key -iv $encrypted_138890a96bfe_iv
      -in aws-note-agility.enc -out ~/.ssh/aws-note-agility -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ~/.ssh/aws-note-agility
    - ssh-add ~/.ssh/aws-note-agility
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-apt python-pycurl
    install:
    - pip install ansible
    script:
    - echo "Tests initial";
    - ansible-playbook ansible/website.yml --syntax-check
    - echo "Deploying in dev";
    - ansible-playbook ansible/website.yml -l aws -t deploy_dev
    - echo "Deployed run with success";
  
  - stage: deploy_prod
    if: branch = master
    script:
    - echo "Tests initial";
    - ansible-playbook ansible/website.yml --syntax-check
    - echo "Deploying in dev";
    - ansible-playbook ansible/website.yml -l aws -t deploy_prod
    - echo "Deployed run with success";
