---
sudo: required
dist: trusty

language: python
python: "2.7"

#cache:
#  directories
#    - python

env:
  - ANSIBLE_VERSION=latest

stages:
  - name: unit-tests
  - name: deploy_dev
  - name: deploy_prd
    if: branch = desenv AND NOT type pull_request

#branches:
#  only:
#  - master
#  - desenv

before_install:
  - sudo apt-get update -qq
  - pip install ansible
  - pip install ansible-lint

#install:
  # Install Ansible.
  #- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
#  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

#script:
#  - ansible-playbook ansible/website.yml --syntax-check
# jobs:
#  include:
#    - stage: test
#      script:
#       # Check the roles playbook website.yml syntax
#        - ansible-playbook ansible/website.yml --syntax-check

jobs:
  include:
    - stage: unit-tests
      scripts:
        - ansible-playbook ansible/website.yml --syntax-check
    - stage: deploy_dev
      scripts:
        - echo "Deploying";
        - ansible-playbook ansible/website.yml -l aws -t deploy_dev
        - echo "Deployed"
