#...
    stages:
      deployment:
        workDir: /home/ubuntu/my-project
        steps:
          - type: deploy
              name: "Deploy to staging"
            command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ];
                then ansible-playbook site.yml -i staging;
              fi
          - type: deploy
              name: "Deploy to production"
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ];
                then ansible-playbook site.yml -i production;
              fi
#...