---
- name: Test nginx e restarted
  command: nginx -t
  notify: [ 'Restart nginx' ]

- name: Test nginx e reload
  command: nginx -t
  notify: [ 'Reload nginx' ]

- name: Restart nginx
  systemd: 
   name: nginx
   enabled: yes
   daemon_reload: yes
   masked: no
   state: restarted

- name: Reload nginx
  command: nginx -s reload