---
- include_vars:
    file: inventory/group_vars/{{perfil}}.yml
  tags:
    - deploy
    
- name: Init State
  command: terraform init -get=true -input=false
  register: _terraform_init_state
  changed_when: false
  args:
     chdir: "{{ project_dir }}"
  tags:
    - terraform_plan

- name: Plan
  terraform:
    project_path: "{{ project_dir }}"
    plan_file: 'tfplan'
    lock: true
    state: planned
  tags: 
    - terraform_plan

- name: Apply
  terraform:
    project_path: "{{ project_dir }}"
    lock: true
    state: present
  tags:
    - terraform_plan
    
- name: Destroy
  terraform:
    project_path: "{{ project_dir }}"
    lock: true
    state: absent
  tags:
    - terraform_destroy
