---
- name: Clone the code {{project_name}} to the docroot desenv
  git:
    repo: "{{project_repo}}"
    dest: "{{project_root}}/dev/{{project_name}}"
    version: desenv
    clone: yes
    update: yes
  notify: Test nginx e reload
  tags:
    - deploy_dev

- name: Clone the code {{project_name}} to the docroot production
  git:
    repo: "{{project_repo}}"
    dest: "{{project_root}}/prod/{{project_name}}"
    version: master
    clone: yes
    update: yes
  notify: Test nginx e reload
  tags:
   - deploy_prod

