---
- name: Update OS
  yum: name="*" state=latest update_cache=yes

- name: Install packages essentials
  yum: name={{item}} state=latest update_cache=yes
  with_items:
   - vim

- name: Copy template nginx.repo
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx web server
  yum: name=nginx state=latest update_cache=yes
  notify:
   - start nginx

- name: Copy templates nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
  - reload nginx