---
- name: Copy template nginx.repo
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo
  
- name: Install nginx web server
  yum: name=nginx state=latest update_cache=yes
  notify: [ 'Test nginx e restarted' ]

- name: Create direcory vhosts
  file: 
   path: /etc/nginx/conf.d/vhosts
   state: directory
   mode: 0755

- name: copy templates nginx.conf/gpit.conf (vhost)
  template: src={{ item.src }} dest={{ item.dest }} mode=0644 owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf, mode: 0644, owner: root, group: root }
    - { src: gpit.conf.j2, dest: /etc/nginx/conf.d/vhosts/gpit.conf, mode: 0644, owner: root, group: root }
  notify: [ 'Test nginx e reload' ]
